### ISSUE TITLE
running regression tests

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#44]
I think we could consider the possibility to run regression tests on travis, maybe with a timer to make sure they run fast enough. Clearly they should be designed ad hoc, and not just using the production plumed.dat with the 100Mb trajectory.

A possible syntax could be
````
plumed_input:
  - path: plumed.dat
    driver: --ixtc traj.xtc
    reference:
      - HILLS
      - COLVAR
  - path: plumed2.dat
    driver: --ixtc traj2.xtc
    reference:
      - HILLS2
      - COLVAR2

````

It overlaps a bit with our own regtests though, so I am not sure it is a good idea. But it could be more suitable for members of the consortium that are not really developing new features (and so rarely get into the github code) but would like to make sure their input files not only can be read (already testing it) but will continue to give the same results.

Any comment?
